Api authorization
easton-morris/m3-0921-code-solutions pull request #31
Opened 2021-11-08 07:56 UTC by easton-morris

2021-11-08 07:56 UTC, easton-morris commented
![image](https://user-images.githubusercontent.com/75236087/140704270-9942a4d9-04cd-46f6-a190-d43faba546da.png)

2021-11-08 07:57 UTC, easton-morris commented
![image](https://user-images.githubusercontent.com/75236087/140704323-44fa53dd-2ec4-4b83-ada6-e9d1caf66616.png)

2021-11-08 07:57 UTC, easton-morris commented
![image](https://user-images.githubusercontent.com/75236087/140704391-5154296b-63ae-4444-b1e3-8b1db92e1958.png)

2021-11-08 23:25 UTC, scbowler requested changes
Looking good, just one update needed. Let me know if you have any questions.

2021-11-08 23:25 UTC, scbowler commented on api-authorization/server/authorization-middleware.js
> +  const xToken = Object.getOwnPropertyDescriptor(req.headers, 'x-access-token');
This is a bit overkill, you can use the `req.headers` object like any other object:

```JAVASCRIPT
cont xToken = req.headers['x-access-token'];
```

2021-11-09 02:38 UTC, scbowler approved these changes
Great job with the update, looks good! 👍

2021-11-09 10:20 UTC, merged