es6-modules
easton-morris/m3-0921-code-solutions pull request #7
Opened 2021-10-03 06:49 UTC by easton-morris

2021-10-03 06:49 UTC, easton-morris commented
do we just screenshot the app?

2021-10-04 17:17 UTC, scbowler commented
> do we just screenshot the app?

A screenshot of the working App and your terminal output after running `npm run build`

2021-10-04 17:32 UTC, scbowler requested changes
Looking good, but a couple updates needed. Let me know if you have any questions.

2021-10-04 17:32 UTC, scbowler commented on es6-modules/src/components/todo-list.js
> +import createElement from '../lib/create-element';
Here you want to import from the `lib/index.js`. We will go over tonight why one is preferred over the other.

```JAVASCRIPT
import { createElement } from '../lib';
```

2021-10-04 17:32 UTC, scbowler commented on es6-modules/src/components/todo-form.js
> +import createElement from '../lib/create-element';
Same here, should be directly from `lib/index.js`

```JAVASCRIPT
import { createElement } from '../lib';
```

2021-10-04 17:32 UTC, scbowler commented on es6-modules/src/components/todo-app.js
> +import { createElement, noop } from '../lib';
This is the benefit of importing from the `lib/index.js`. You can import multiple things from the `lib` folder on 1 line.

2021-10-05 01:37 UTC, easton-morris commented
![image](https://user-images.githubusercontent.com/75236087/135946902-74d6ab4a-5019-4659-9d37-8f0f3c359cff.png)

2021-10-05 01:38 UTC, easton-morris commented
![image](https://user-images.githubusercontent.com/75236087/135946946-87fc2808-e56c-4913-9afb-6782f7a6fa1d.png)

2021-10-05 02:31 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2021-10-05 02:31 UTC, merged